### ISSUE TITLE
Detect a drive type

### ISSUE THREAD

**Issue by jviotti** [balena-io-modules/drivelist#64]
For example, determine if a drive is a USB drive, an SDCard, an SSD HD, etc.

**Comment by dlech** [comment]
Windows: In the WMI [Win32_DiskDrive class](https://msdn.microsoft.com/en-us/library/aa394132(v=vs.85).aspx), there is an InterfaceType property

```
InterfaceType

    Data type: string
    Access type: Read-only
    Qualifiers: MappingStrings ("Win32API|Device Input and Output Functions|DeviceIoControl")

    Interface type of physical disk drive.

    The values are:

    SCSI

    HDC

    IDE

    USB

    1394
```

macOS: `diskutil info` returns a "Protocol" property that is similar. According to [this page](https://developer.apple.com/library/content/documentation/DriversKernelHardware/Conceptual/DiskArbitrationProgGuide/ArbitrationBasics/ArbitrationBasics.html), it should match [kIOPropertyPhysicalInterconnect*](https://developer.apple.com/reference/iokit/1658874-iostorageprotocolcharacteristics/1658921-defines?language=objc), but on my computer, I just see "USB" and "PCI". "PCI" isn't in the header file, so I'm not sure if this is quite right. Additionally, the SD card reader still shows up as USB because internally it is USB.

Linux: It [looks like we already have the info we need to detect USB and SD](https://github.com/resin-io-modules/drivelist/blob/master/scripts/linux.sh#L56).

---

These methods of detection are less than ideal, but it's a start. I think in actual practice though, almost everything will be detected as a USB drive.

**Comment by jviotti** [comment]
Hi @dlech,

Thanks for the very valuable investigations! Its a pity that "USB" is the best we can get. I say lets keep pushing for a way to at least say if a drive is an SDCard. I bet this is possible somehow, since all operating systems are able to reliably show SDCard desktop icons for the drive.

> Linux: It looks like we already have the info we need to detect USB and SD.

Are you aware of a udev property to perform this? Can you link me to any documentation?

**Comment by Dayjo** [comment]
The macOS `diskutil` returns something like this for a USB Flash drive;

```
Device Identifier:        disk1s1
   Device Node:              /dev/disk1s1
   Whole:                    No
   Part of Whole:            disk1
   Device / Media Name:      Untitled 1

   Volume Name:              DAYJOS USB

   Mounted:                  Yes
   Mount Point:              /Volumes/DAYJOS USB

   File System Personality:  MS-DOS FAT16
   Type (Bundle):            msdos
   Name (User Visible):      MS-DOS (FAT16)

   Partition Type:           DOS_FAT_16
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported
   Volume UUID:              2532FA31-46B3-3FEA-B37F-9D958B64CB67

   Total Size:               501.2 MB (501170176 Bytes) (exactly 978848 512-Byte-Units)
   Volume Free Space:        471.5 MB (471506944 Bytes) (exactly 920912 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    8192 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          External
   Removable Media:          No
```

It'd be great to implement this, the one thing I felt that drivelist is missing is the user friendly name of the drive too which is available on this macOS call, not sure about Windows however.

**Comment by jviotti** [comment]
Hi @Dayjo ,

The "user friendly" name (in this case "DAYJOS USB" I assume) should be shown in the `description` property already. Do you get it there? If not, what are you getting instead?

**Comment by Dayjo** [comment]
Hello @jviotti,

Unfortunately not, here's what I get for the same disk using drivelist;

```json
{
     device: '/dev/disk2',
     description: 'Flash Disk',
     size: 501219328,
     mountpoint: '/Volumes/DAYJOS USB',
     name: '/dev/disk2',
     raw: '/dev/rdisk2',
     protected: false,
     system: true
}
```

**Comment by dlech** [comment]
@Dayjo, first, it would be better if you opened a new issue for this so we don't confuse it with the original issue about the drive "type". Your issue seems to be about the drive "name".

FYI, the "description" on macOS is coming from [here](https://github.com/resin-io-modules/drivelist/blob/master/scripts/darwin.sh#L22)

**Comment by jviotti** [comment]
@Dayjo, I agree with @dlech about opening a new issue for this. I find strange that you get a "Flash Disk" description when I don't see that in your `diskutil` output. Can you show us the output of `diskutil info /dev/diskX`, where X is the right disk number?

**Comment by Dayjo** [comment]
@dlech sure :) I just wasn't sure if it was actually an issue. 

As for the 'type', I'm was previously using 'system' to determine if it was an external USB drive or not but this doesn't work as the one above appears as 'system' even though it's a USB drive. Presumably because for some reason it thinks Removable Media is false (this could just be a flaw in Mac `diskutil`)

**Comment by lurch** [comment]
> I bet this is possible somehow, since all operating systems are able to reliably show SDCard desktop icons for the drive.

I was experimenting with a whole bunch of different USB SD card-readers last night on Ubuntu 14.04, and some showed up in the side-bar with an SD card icon, most showed up with just a generic USB drive icon, and one even showed up with a CompactFlash icon!

**Comment by Dayjo** [comment]
@lurch I reckon there's a total lack of standardisation across manufacturers, same as why one is recognised as a flash drive and one is thought to be 'system'

**Comment by lurch** [comment]
Hmm, I wonder if it's possible to work out which USB device a particular disk corresponds to, and from there work out the USB VID and PID?
We could theoretically then store a list of VIDs & PIDs for "known SD card readers", "known USB Flash drives", "known USB HDDs", etc. Although such a list would obviously always be _woefully_ incomplete ;-)

> Additionally, the SD card reader still shows up as USB because internally it is USB.

Sometimes the internal SD card reader is connected on a laptop via USB (like on my previous laptop), in which case it appears as `/dev/sdX` under Linux; and sometimes it's connected via PCI (like on my current laptop), in which case it appears as `/dev/mmcblk0`. When the card-reader appears as `/dev/sdX` you only ever get a block-based interface (same as with a USB Flash thumbdrive), but when it appears as `/dev/mmcblkX` you also get access to the card's internal parameters e.g. http://www.cameramemoryspeed.com/sd-memory-card-faq/reading-sd-card-cid-serial-psn-internal-numbers/

So @jviotti if the disk is detected as `/dev/mmcblkX` it's 99% likely to be an SD card? :)

**Comment by jviotti** [comment]
> So @jviotti if the disk is detected as /dev/mmcblkX it's 99% likely to be an SD card? :)

I don't know for sure, but I'd expect that your assumption is right.

**Comment by jhermsmeier** [comment]
Closing, as this has been added under the `.enumerator` and `.busType` properties in #243 (v6.0.0)

**Comment by lurch** [comment]
But that's only for Windows, right? Should we keep this issue open until the Linux and Darwin versions also report this info?

**Comment by Frobitz66** [comment]
For Darwin try:  ```system_profiler SPCardReaderDataType SPUSBDataType SPSmartCardsDataType```

The available data type nouns can be listed with ```system_profiler -listDataTypes```

**Comment by jviotti** [comment]
Closing stale issues
